### ISSUE TITLE
Training environment on the local machine

### ISSUE THREAD

**Issue by Wilboludriver** [Digital-Humans-23/a2#19]
Hi, I'm tring to set the environment on my laptop to train ex 3 to save time (as others have already posted), but I alway got erros such as not finding certain libraries. I'm wondering which system libraries are necessary for the training (all of the packagies loaded in `module load gcc/8.2.0 python/3.9.9 cmake/3.25.0 freeglut/3.0.0 libxrandr/1.5.0  libxinerama/1.1.3 libxi/1.7.6  libxcursor/1.1.14 mesa/17.2.3 eth_proxy` ? )

**Comment by MiguelZamoraM** [comment]
The command `module load ...`  is specific to the server environment. You don't need that to run the experiments on your local machine. But you need to make sure that you have installed those libraries in your Linux environment (`cmake`, `freeglut`, `libxrandr`, ...).  

The only library that you don't need in your machine is `eth_proxy` as that is also specific to the server environment.

**Comment by Wilboludriver** [comment]
> The command `module load ...` is specific to the server environment. You don't need that to run the experiments on your local machine. But you need to make sure that you have installed those libraries in your Linux environment (`cmake`, `freeglut`, `libxrandr`, ...).
> 
> The only library that you don't need in your machine is `eth_proxy` as that is also specific to the server environment.

Thanks very much. It's solved!
