### ISSUE TITLE
[ex.3] Joint angle cannot pass the test

### ISSUE THREAD

**Issue by dehezhang2** [Digital-Humans-23/a2#2]
May I ask a question about the joint angle calculation? It seems that my calculation has a small error:
<img width="845" alt="Screen Shot 2023-03-18 at 10 02 19 PM" src="https://user-images.githubusercontent.com/40571743/226139924-55d89adb-18a9-4c94-9872-2f7e6aa75d51.png">
In the task description, the number of joints is 43, but in the `ObservationData` class the size of the `joint_angles` array is 44. Is it possible that this mismatch caused the error?

**Comment by steinraf** [comment]
I am also getting a similarly offset of 0.009954251707404079. 

As a side question, does the calculation of your torque work for the dog gaussian and the human reward?

**Comment by dehezhang2** [comment]
> 

The torque part can pass the test.

**Comment by yitongx** [comment]
I also encountered the same issue. 

Obtained: 0.00995425170740408
Expected: 0.009990833552124415 ± 1.0e-08

**Comment by MiguelZamoraM** [comment]
There was a small error creating the test case for Bob.  I'm training Bob again to make sure that everything works.  
I will update that test case during the day.

**Comment by MiguelZamoraM** [comment]
- Download this [file](https://github.com/Digital-Humans-23/a2/blob/main/src/python/tests/pickled_files/test_data_bob1679334591.29026.pickle) and put it under `src/src/python/tests/pickled_files/`. 

- Add the file to the repo using:  `git add test_data_bob1679334591.29026.pickle`

- Update the variable  `pickle_path` in `line 8` of  `src/python/tests/03_test_human_reward.py` to reflect the changes i.e:
`pickle_path = '/pickled_files/test_data_bob1679334591.29026.pickle'`

-  Commit and push the changes. Correct implementations should pass the test.

**Comment by dehezhang2** [comment]
> 

Should we also change the directory in `line 8` of the file `./src/python/tests/03_test_human_reward.py`?

**Comment by MiguelZamoraM** [comment]
Yes. Please update the variable `pickle_path` in line 8 of  `src/python/tests/03_test_human_reward.py` to reflect the changes i.e:
`pickle_path = '/pickled_files/test_data_bob1679334591.29026.pickle'`

**Comment by drlxj** [comment]
Do you also change the number of joints from 43 to 44? I pass the test if I choose 44, but in Readme the variable is requested to be 43.

**Comment by MiguelZamoraM** [comment]
@drlxj The actual number of joints is 44. I just fixed the typo on the README.
