### ISSUE TITLE
Ex. 2: Incorrect torque reward formulation?

### ISSUE THREAD

**Issue by rabaur** [Digital-Humans-23/a2#3]
I think the formulation given in the README.md for the torque reward in exercise 2 is wrong. The weight term should be outside the exponential. Before doing so, the tests fail (but moving it out works)
![torque](https://user-images.githubusercontent.com/74608072/226200836-6e602a36-3d57-4614-81ef-46a93b31a770.png)

**Comment by MiguelZamoraM** [comment]
That is a typo on the README. Indeed the right expression for torque is:  $w_{\tau} \text{exp}(-\Vert \mathbf{\tau} \Vert_2^2 / (2 N \sigma_t^2))$

I just fixed it on the README. Thanks for mentioning it!
