### ISSUE TITLE
stable_baselines3 cannot be found && module load python/3.9.9

### ISSUE THREAD

**Issue by juhe9842** [Digital-Humans-23/a2#6]
Dear TAs

I noticed that whenever I load python/3.9.9 on the cluster, there will be an error message telling me that stable_baselines3 cannot be found. Instead, the training works fine on the cluster without python/3.9.9. So I'm curious if this module is actually necessary? Does it have anything to do with the training performance or I don't have to worry about it as long as it starts to train.

Junzhe He

**Comment by MiguelZamoraM** [comment]
As long as your training works it should be fine. stable_baselines3 is definitely necessary. If your training started it means the job has found a proper environment with stable_baslines3 installed despite the error messages that the server prints.

It might be worth taking a look at this [issue](https://github.com/Digital-Humans-23/a2/issues/4)  as well.

**Comment by juhe9842** [comment]
Thank you!
