### ISSUE TITLE
VSCode Debugger

### ISSUE THREAD

**Issue by mizeller** [Digital-Humans-23/a2#9]
2 basic questions for getting started with this assignment:

Is there a way to place a debug checkpoint i.e. in `quadratic_reward.py` and stop there?
Also, is there a way to use the VSCode testing feature for the tests?

Thank you in advance! :-)

**Comment by MiguelZamoraM** [comment]
- Yes. You can place debug checkpoints in files like `quadratic_reward.py`
- Yes. You can do this with VS code.
  - Install the Python extension. (Only the last extension in the image below should be enough).   
![image](https://user-images.githubusercontent.com/40716457/226927089-41214973-be2e-492a-8bb2-d64488fb8d5c.png)

  - Choose your conda env (pylocoEnv) as the interpreter. (Press `Ctrl+Shift+P` and search for the option: `Python: Select interpreter`)   
![image](https://user-images.githubusercontent.com/40716457/226927424-66289e25-fab9-411b-87f7-d3702a78dae0.png)

  - Create a lunch file (`launch.json`) in the `.vscode` folder. 
![image](https://user-images.githubusercontent.com/40716457/226927557-53b8be3f-79ed-46ce-a628-941eb43d6be1.png)

  - Pass the arguments that you would pass to train with the dog with a quadratic reward. Your launch file should look something like this: 
![image](https://user-images.githubusercontent.com/40716457/226928341-bb2016f2-a7f9-4dff-a09d-9d3160a434f9.png)


  - Run the main file: 
![image](https://user-images.githubusercontent.com/40716457/226928600-eda04a29-2fb4-43be-92ec-49122fbb7ec0.png)

  - The debugger should stop at the desired breakpoint:  
![image](https://user-images.githubusercontent.com/40716457/226929129-ff60d472-6aae-4fec-9b50-7489c4b25099.png)

**Comment by mizeller** [comment]
great thanks! i didn't know about the launch.json step...

**Comment by mizeller** [comment]
Remark: I also had to add the debug argument in the `launch.json`, otherwise it would crash on line 67 in `scripts.py`.
